/* eslint-disable */
// Generated by Wrangler - simplified to just Env types
// Runtime types come from @cloudflare/workers-types

// Text file imports (for Wrangler rules)
declare module '*.html' {
    const content:string;
    export default content;
}

declare module '*.css' {
    const content:string;
    export default content;
}

declare namespace Cloudflare {
    interface Env {
        ASSETS;
        TAP_SERVER_URL:string;
        TAP_ADMIN_PASSWORD:string;
        API_AUTH_TOKEN:string;
        // Passkey auth
        REGISTRATION_SECRET:string;
        taproom_auth:D1Database;
        AUTH_CHALLENGES:KVNamespace;
        // Fly.io integration for TAP server config
        FLY_API_TOKEN:string;
        FLY_TAP_APP_NAME:string;
    }
}

interface Env extends Cloudflare.Env {}

